-- Migração isolada para o conteúdo da home.
-- Execute no SQL Editor do Supabase se a tabela public.home_content ainda não existir no projeto remoto.
-- Depois de rodar, refresque o schema cache no painel do Supabase, se necessário.

CREATE TABLE IF NOT EXISTS public.home_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  image_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS home_content_section_idx ON public.home_content(section);
CREATE INDEX IF NOT EXISTS home_content_updated_at_idx ON public.home_content(updated_at DESC);

INSERT INTO storage.buckets (id, name, public)
VALUES ('home-images', 'home-images', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Allow public read home content" ON public.home_content;
DROP POLICY IF EXISTS "Allow public write home content" ON public.home_content;
DROP POLICY IF EXISTS "Allow public read home images" ON storage.objects;
DROP POLICY IF EXISTS "Allow public write home images" ON storage.objects;
DROP POLICY IF EXISTS "Allow public update home images" ON storage.objects;
DROP POLICY IF EXISTS "Allow public delete home images" ON storage.objects;

CREATE POLICY "Allow public read home content" ON public.home_content
  FOR SELECT TO public
  USING (true);

CREATE POLICY "Allow public write home content" ON public.home_content
  FOR ALL TO public
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow public read home images" ON storage.objects
  FOR SELECT TO public
  USING (bucket_id = 'home-images');

CREATE POLICY "Allow public write home images" ON storage.objects
  FOR INSERT TO public
  WITH CHECK (bucket_id = 'home-images');

CREATE POLICY "Allow public update home images" ON storage.objects
  FOR UPDATE TO public
  USING (bucket_id = 'home-images')
  WITH CHECK (bucket_id = 'home-images');

CREATE POLICY "Allow public delete home images" ON storage.objects
  FOR DELETE TO public
  USING (bucket_id = 'home-images');

INSERT INTO public.home_content (section, title, description, image_url, updated_at)
VALUES
  (
    'hero',
    '63 anos de um trabalho de amor!',
    'O CACS | Complexo Assistencial Cairbar Schutel, organização filantrópica sem fins lucrativos, foi criado em 17 de janeiro de 1963 movido pela busca de uma sociedade mais justa e com mais oportunidades.',
    'assets/img/hero-bg.jpg',
    now()
  ),
  (
    'sobre',
    'CACS',
    'O CACS | Complexo Assistencial Cairbar Schutel, organização filantrópica sem fins lucrativos, fundado em 17 de janeiro de 1963, movido pela busca de uma sociedade mais justa e com mais oportunidades, trabalhando para resgatar a dignidade e fomentar a autonomia de pessoas em situação de vulnerabilidade.',
    'assets/img/Home-CACS.jpeg',
    now()
  ),
  (
    'servicos',
    'Programa de Acolhimento',
    'O Acolhimento Psicológico oferece atendimento gratuito para pessoas em situação de vulnerabilidade social em São Paulo, com psicólogos voluntários qualificados.',
    'assets/img/7. Acolhimento Psicológico.png',
    now()
  )
ON CONFLICT (section) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  image_url = EXCLUDED.image_url,
  updated_at = EXCLUDED.updated_at;
